<script>
    import ScrollEffect from './ScrollEffect.svelte';

    let artCollaborations = [
        {
            title: "BITZ",
            link: "/work/bitz",
            image: "img/bitz/bitz_logo.jpg",
            description: "A digital tool for identifying and learning about the organisms around you. S+T+ARTS EU residency.",
            year: 2025
        },

        {
            title: "WTFood",
            link: "work/wtfood",
            image: "img/wtfood.png",
            description: "Using AI to uncover the glitches of the food system. S+T+ARTS EU residency.",
            year: 2024
        },
    ]

    let educationProjects = [
        {
            title: "Visualizing RAGs",
            link: "/work/visualizing-rags",
            image: "img/rags.jpg",
            description: "Teaching tool to explain the inner workings of AI question-answering systems through interactive visualization.",
            year: 2025
        },
        {
            title: "Tic-tac-toe matchbox AI",
            link: "/blog/menace",
            image: "img/menace.jpg",
            description: "Mechanical learning system from the 1960s using matchboxes to learn tic-tac-toe, demonstrating fundamental AI principles with everyday objects.",
            year: 2024
        },
        {
            title: "Drawing2Map",
            link: "/work/drawing2map",
            image: "img/drawing2map/thumb.jpg",
            description: "Web interface for Seg2Sat that helps users understand the relationship between hand-drawn concepts and satellite imagery. Built using HuggingFace's inference endpoint.",
            year: 2023
        }
    ];

    let genAIProjects = [
        {
            title: "GouvX",
            link: "work/gouvx",
            image: "img/gouvx/gouvx_logo.jpg",
            description: "A chatbot using retrieval augmented generation to help you navigate French law.",
            year: 2023
        },
        {
            title: "Seg2Sat",
            link: "https://github.com/RubenGres/Seg2Sat",
            image: "img/seg2sat.jpg",
            description: "Create aerial view images in any style you want. Project made with IGN FLAIR1 dataset, StableDiffusion, and ControlNet.",
            year: 2023
        },
        {
            title: "ControlMeme",
            link: "https://meme.koll.ai",
            image: "img/controlmeme.jpg",
            description: "Generate variations of popular memes using StableDiffusion and ControlNet. Share your creations in the gallery.",
            year: 2023
        },
        {
            title: "Infinite Canvas",
            link: "https://rubengr.es/blog/infinitecanvas/",
            image: "img/canvas.jpg",
            description: "Start creating with others using AI image generation in this shared infinite canvas. Powered by StableDiffusion and ReactJS.",
            year: 2022
        },
        {
            title: "This SCP does not exist",
            link: "https://www.thisscpdoesnotexist.com/",
            image: "img/tsdne.jpg",
            description: "Generate custom SCP from a simple prompt using GPT4. Over three thousand entities have been generated by the community.",
            year: 2021
        }
    ];

    let gameProjects = [
        {
            title: "Dad knows (siege) best",
            link: "https://www.youtube.com/watch?v=ofAcTvuybvY",
            image: "img/siege.jpg",
            description: "Lead an army of LLM soldier agents from the grave. Built during Mistral x HF Hackaton 2025.",
            year: 2025
        },
        {
            title: "Zoomies: Fast or fired",
            link: "https://ohmlet.itch.io/zoomies",
            image: "https://img.itch.zone/aW1nLzE3NDQ4OTYxLmpwZw==/315x250%23c/p%2BHryy.jpg",
            description: "Play as an exploited employee in corporate hell. GMTK 2024 GameJam.",
            year: 2024
        },
        {
            title: "SnipIt",
            link: "https://ohmlet.itch.io/snip-it",
            image: "img/snipit.jpg",
            description: "Snip away and explore famous paintings in a whole new dimension. First place in the 2023 Hugging Face Game JAM.",
            year: 2023
        },
        {
            title: "Pug Heist",
            link: "https://ohmlet.itch.io/pug-heists",
            image: "img/pug.jpg",
            description: "A strange little puzzle game made for GTMK 2022. Solve every level and escape to safety.",
            year: 2022
        },
        {
            title: "Unwanted Roommate",
            link: "https://ohmlet.itch.io/unwanted-roommate",
            image: "img/unwantedroommate.jpg",
            description: "Deal with your inescapable anxiety, your unwanted roommate. Made for GMTK 2021 Game Jam",
            year: 2021
        },
        {
            title: "VR Handglider",
            link: "https://github.com/RubenGres/VRHanglider",
            image: "img/planeur.jpg",
            description: "Procedural world generator and flight simulator in VR using Unity. The plane is controlled via a microcontroller.",
            year: 2020
        },
        {
            title: "Out Of Control(s)",
            link: "https://ohmlet.itch.io/out-of-controls",
            image: "img/outofcontrols.jpg",
            description: "You have a limited number of key presses before you run out of controls. Made for GMTK 2020 Game Jam.",
            year: 2020
        },
        {
            title: "Blastoff",
            link: "https://github.com/RubenGres/Blastoff",
            image: "img/blastoff.jpg",
            description: "Procedural mining game in Java. Custom game engine, perlin noise, and cellular automatas for terrain generation.",
            year: 2018
        }
    ];

    let otherProjects = [
        {
            title: "This website",
            link: "/",
            image: "img/portfolio.jpg",
            description: "Wow so meta. Statically built with SvelteKit and Bootstrap. No template cause I'm a special boy.",
            year: 2022 
        },
        {
            title: "TVShow Ratings",
            link: "https://rubengres.github.io/TvShowRatings/index.html",
            image: "img/tvshowratings.jpg",
            description: "View TV show IMDB ratings in a simple, comprehensive way. Built using Angular, jQuery, and OMDB API for data.",
            year: 2020
        },
        {
            title: "Bad Apple Animation",
            link: "https://www.youtube.com/watch?v=LD4D09EVcDY&t=112s",
            image: "img/badapple.jpg",
            description: "A Blender animation of the opening of Bad Apple rendered on an Etch-A-Sketch. The video is currently reaching 333k views!",
            year: 2020
        },
        {
            title: "Flocking Sandbox",
            link: "https://github.com/RubenGres/FlockingSandbox",
            image: "img/boidsjs.jpg",
            description: "Boids algorithm in p5.js. You can spawn a fish or a shark; the sharks will try to eat the fishes as they try to escape.",
            year: 2020
        }
        
    ];

    let projectCategories = [
        {
            title: "Artistic collaborations",
            id: "art",
            description: `
                <p> I work alongside artists in residency, bringing AI, data visualization, and development expertise to their creative practice.
                Our work has been presented at Rotterdam's Nieuw Instituut, Belgrade's Palace of Science, and other international venues. </p>
            `,
            projects : artCollaborations
        },
        {
            title: "Educational Tools",
            id: "education",
            description: `
                <p>I believe in making complex AI concepts accessible through hands-on learning and visual tools.
                I teach at graduate level (ENSG) and work with educational organizations to bring AI education to younger audiences.</p>
            `,
            projects: educationProjects
        },
        {
            title: "Generative AI projects",
            id: "genai",
            description: `
                <p> I explore generative AI to develop practical applications and creative tools for diverse audiences.
                I co-founded <a href="http://latentminds.co">LatentMinds</a>, where we develop experimental tools that redefine the boundaries of AI-assisted creativity.</p>
            `,
            projects : genAIProjects
        },
        {
            title: "Game development",
            id: "games",
            description: `
                <p> I explore unconventional gameplays through game jams, personal projects, and a bigger game soon to be announced.
                I collaborate with friends within <a href="https://ohmlet.itch.io">Ohmlet studio</a>, a collective making experimental games.</p>
            `,
            projects : gameProjects
        },
        {
            title: "Miscellaneous projects",
            id: "misc",
            description:`
                <p>Diverse experiments and older projects<p>
            `,
            projects : otherProjects
        },
    ]
</script>

<ScrollEffect>
    {#each projectCategories as category}
        <section style="padding-left: 13px; padding-right: 13px; margin-bottom: 100px;" id="{category.id}">
            <div class="container" style="max-width: 1000px;">

                <div class="row">
                    <div class="col-12">
                        <div style="padding-bottom: 30px;">
                            <h2 class="text-uppercase" style="letter-spacing: 0.15em;">
                                {category.title}
                                <span class="colored-dash"></span>
                            </h2>
                            <h4 style="line-height: 1.4em;">
                                {@html category.description}
                            </h4>
                        </div>
                    </div>
                </div>

                <div class="row g-4 justify-content-center" style="margin: auto">
                    {#each category.projects as project}
                        <div class="col-lg-4 col-md-4 col-sm-6 col-12" style="margin-bottom: 50px; display: flex; justify-content: center;">
                            <div class="h-100">
                                <a href="{project.link}" class="text-decoration-none">
                                    <div class="card h-100 border-0 shadow-sm"  style="width: 300px">
                                        <div class="overflow-hidden">
                                        <center>
                                           <img src={project.image} alt={project.title} class="card-img-top" style="margin: auto; height: 300px; width: auto; object-fit: cover; aspect-ratio: 1;">
                                        </center>
                                        </div>
                                        <div class="card-body">
                                            <h4 style="text-transform: uppercase; color: black; margin-bottom: 5px">
                                                {project.title} 
                                                <small class="fw-normal text-muted">({project.year})</small>
                                            </h4>
                                            <p class="card-text text-muted" style="line-height: 1.2em;">{project.description}</p>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                    {/each}
                </div>

            </div>
        </section>
    {/each}
</ScrollEffect>

<style>

.colored-dash {
    position: relative;
    top: -2px;
    display: inline-block;
    margin-left: 5px;
    width: 80px;
    height: 4px;
    background: -webkit-linear-gradient(90deg, #456df3 0%, #e66cb8 100%);
    background: -moz-linear-gradient(90deg, #456df3 0%, #e66cb8 100%);
    background: -o-linear-gradient(90deg, #456df3 0%, #e66cb8 100%);
    background: linear-gradient(90deg, #456df3 0%, #e66cb8 100%);
    filter: blur(1px);
    -o-filter: blur(1px);
    -ms-filter: blur(1px);
    -moz-filter: blur(1px);
    -webkit-filter: blur(1px);
    border-radius: 5px;
}

</style>