<script>
    import ScrollEffect from './ScrollEffect.svelte';
    import { onMount } from 'svelte';

    let artCollaborations = [
        {
            title: "BITZ",
            link: "/work/bitz",
            image: "img/bitz/bitz_logo.jpg",
            description: "A digital tool for identifying and learning about the organisms around you. S+T+ARTS EU residency.",
            year: 2025
        },
        {
            title: "WTFood",
            link: "work/wtfood",
            image: "img/wtfood.png",
            description: "Using AI to uncover the glitches of the food system. S+T+ARTS EU residency.",
            year: 2024
        },
    ]

    let educationProjects = [
        {
            title: "Visualizing RAGs",
            link: "/work/visualizing-rags",
            image: "img/rags.jpg",
            description: "Teaching tool to explain the inner workings of AI question-answering systems through interactive visualization.",
            year: 2025
        },
        {
            title: "Tic-tac-toe matchbox AI",
            link: "/blog/menace",
            image: "img/menace.jpg",
            description: "Mechanical learning system from the 1960s using matchboxes to learn tic-tac-toe, demonstrating fundamental AI principles with everyday objects.",
            year: 2024
        },
        {
            title: "Drawing2Map",
            link: "/work/drawing2map",
            image: "img/drawing2map/thumb.jpg",
            description: "Web interface for Seg2Sat that helps users understand the relationship between hand-drawn concepts and satellite imagery. Built using HuggingFace's inference endpoint.",
            year: 2023
        }
    ];

    let genAIProjects = [
        {
            title: "GouvX",
            link: "work/gouvx",
            image: "img/gouvx/gouvx_logo.jpg",
            description: "A chatbot using retrieval augmented generation to help you navigate French law.",
            year: 2023
        },
        {
            title: "Seg2Sat",
            link: "https://github.com/RubenGres/Seg2Sat",
            image: "img/seg2sat.jpg",
            description: "Create aerial view images in any style you want. Project made with IGN FLAIR1 dataset, StableDiffusion, and ControlNet.",
            year: 2023
        },
        {
            title: "Infinite Canvas",
            link: "https://rubengr.es/blog/infinitecanvas/",
            image: "img/canvas.jpg",
            description: "Start creating with others using AI image generation in this shared infinite canvas. Powered by StableDiffusion and ReactJS.",
            year: 2022
        },
        {
            title: "This SCP does not exist",
            link: "https://www.thisscpdoesnotexist.com/",
            image: "img/tsdne.jpg",
            description: "Generate custom SCP from a simple prompt using GPT4. Over three thousand entities have been generated by the community.",
            year: 2021
        }
    ];

    let gameProjects = [
        {
            title: "Dad knows (siege) best",
            link: "https://www.youtube.com/watch?v=ofAcTvuybvY",
            image: "img/siege.jpg",
            description: "Lead an army of LLM soldier agents from the grave. Built during Mistral x HF Hackaton 2025.",
            year: 2025
        },
        {
            title: "Zoomies",
            link: "https://ohmlet.itch.io/zoomies",
            image: "https://img.itch.zone/aW1nLzE3NDQ4OTYxLmpwZw==/315x250%23c/p%2BHryy.jpg",
            description: "Play as an exploited employee in corporate hell. GMTK 2024 GameJam.",
            year: 2024
        },
        {
            title: "SnipIt",
            link: "https://ohmlet.itch.io/snip-it",
            image: "img/snipit.jpg",
            description: "Snip away and explore famous paintings in a whole new dimension. First place in the 2023 Hugging Face Game JAM.",
            year: 2023
        },
        {
            title: "Pug Heist",
            link: "https://ohmlet.itch.io/pug-heists",
            image: "img/pug.jpg",
            description: "A strange little puzzle game made for GTMK 2022. Solve every level and escape to safety.",
            year: 2022
        },
        {
            title: "Unwanted Roommate",
            link: "https://ohmlet.itch.io/unwanted-roommate",
            image: "img/unwantedroommate.jpg",
            description: "Deal with your inescapable anxiety, your unwanted roommate. Made for GMTK 2021 Game Jam",
            year: 2021
        },
        {
            title: "VR Handglider",
            link: "https://github.com/RubenGres/VRHanglider",
            image: "img/planeur.jpg",
            description: "Procedural world generator and flight simulator in VR using Unity. The plane is controlled via a microcontroller.",
            year: 2020
        },
        {
            title: "Out Of Control(s)",
            link: "https://ohmlet.itch.io/out-of-controls",
            image: "img/outofcontrols.jpg",
            description: "You have a limited number of key presses before you run out of controls. Made for GMTK 2020 Game Jam.",
            year: 2020
        },
        {
            title: "Blastoff",
            link: "https://github.com/RubenGres/Blastoff",
            image: "img/blastoff.jpg",
            description: "Procedural mining game in Java. Custom game engine, perlin noise, and cellular automatas for terrain generation.",
            year: 2018
        }
    ];

    let otherProjects = [
        {
            title: "This website",
            link: "/",
            image: "img/portfolio.jpg",
            description: "Wow so meta. Statically built with SvelteKit and Bootstrap. No template cause I'm a special boy.",
            year: 2022 
        },
        {
            title: "TVShow Ratings",
            link: "https://rubengres.github.io/TvShowRatings/index.html",
            image: "img/tvshowratings.jpg",
            description: "View TV show IMDB ratings in a simple, comprehensive way. Built using Angular, jQuery, and OMDB API for data.",
            year: 2020
        },
        {
            title: "Bad Apple Animation",
            link: "https://www.youtube.com/watch?v=LD4D09EVcDY&t=112s",
            image: "img/badapple.jpg",
            description: "A Blender animation of the opening of Bad Apple rendered on an Etch-A-Sketch. The video is currently reaching 333k views!",
            year: 2020
        },
        {
            title: "Flocking Sandbox",
            link: "https://github.com/RubenGres/FlockingSandbox",
            image: "img/boidsjs.jpg",
            description: "Boids algorithm in p5.js. You can spawn a fish or a shark; the sharks will try to eat the fishes as they try to escape.",
            year: 2020
        }
    ];

    let projectCategories = [
        {
            title: "🖼️ Creative Tech for Artists",
            id: "art",
            description: `
                <p> I work alongside artists in residency, bringing AI, data visualization, and development expertise to their creative practice.
                Our work has been presented at Rotterdam's Nieuw Instituut, Belgrade's Palace of Science, and other international venues. </p>
            `,
            projects : artCollaborations
        },
        {
            title: "👨‍🏫 Interactive Tools for Education",
            id: "education",
            description: `
                <p>I believe in making complex AI concepts accessible through hands-on learning and visual tools.
                I teach at graduate level and work with educational organizations to bring AI education to younger audiences.</p>
            `,
            projects: educationProjects
        },
        {
            title: "🧠 Generative AI projects",
            id: "genai",
            description: `
                <p> I explore generative AI to develop practical applications and creative tools for diverse audiences.
                I co-founded <a href="http://latentminds.co">LatentMinds</a>, where we develop experimental tools that redefine the boundaries of AI-assisted creativity.</p>
            `,
            projects : genAIProjects
        },
        {
            title: "🎮 Game development",
            id: "games",
            description: `
                <p> I explore unconventional gameplays through game jams, personal projects, and a commercial game soon to be announced.
                I collaborate with friends within <a href="https://ohmlet.itch.io">Ohmlet studio</a>, a collective making small experimental games.</p>
            `,
            projects : gameProjects
        },
        {
            title: "👾 Miscellaneous projects",
            id: "misc",
            description:`
                <p>Experiments, 3D modeling and older projects that didn't fit in any category.<p>
            `,
            projects : otherProjects
        },
    ]

    let collapsedSections = {};

    for (let category of projectCategories) {
        collapsedSections[category.id] = true;
    }

    // Sphere functionality
    let sphereVisible = false;
    let sphereScale = 0;
    let sphereOpacity = 0;
    let sphereX = 0;
    let sphereY = 0;
    let targetX = 0;
    let targetY = 0;
    let currentImageIndex = 0;
    let currentProjects = [];
    let animationFrame;
    let imageTimerInterval;
    let windowWidth = 0;
    
    // Generate curved text from project names
    $: curvedText = currentProjects.length > 0 
        ? (currentProjects.map(p => p.title.toUpperCase()).join(' • ') + ' • ').repeat(5).slice(0, 66) + "..."
        : 'SNEAK PEEK • '.repeat(8);

    function updateSpherePosition() {
        // Smooth following with delay (faster movement)
        const lerp = 0.03;
        sphereY += (targetY - sphereY) * lerp;
        
        // Animate scale and opacity together
        const targetScale = sphereVisible ? 1 : 0;
        const targetOpacity = sphereVisible ? 1 : 0;
        const scaleLerp = 0.15;
        const opacityLerp = 0.12;
        
        sphereScale += (targetScale - sphereScale) * scaleLerp;
        sphereOpacity += (targetOpacity - sphereOpacity) * opacityLerp;
        
        if (sphereVisible || sphereScale > 0.01 || sphereOpacity > 0.01) {
            animationFrame = requestAnimationFrame(updateSpherePosition);
        }
    }

    function handleMouseMove(event) {
        if (sphereVisible) {
            // Offset position to lower right to avoid blocking view
            targetY = event.clientY - 100;
        }
    }

    function startImageTimer() {
        // Clear any existing timer
        if (imageTimerInterval) {
            clearInterval(imageTimerInterval);
        }
        
        // Set up new timer to change image every 1 second
        imageTimerInterval = setInterval(() => {
            if (sphereVisible && currentProjects.length > 0) {
                currentImageIndex = (currentImageIndex + 1) % currentProjects.length;
            }
        }, 1000); // 1000ms = 1 second
    }

    function stopImageTimer() {
        if (imageTimerInterval) {
            clearInterval(imageTimerInterval);
            imageTimerInterval = null;
        }
    }

    function startSphereEffect(projects) {
        // Only show sphere on larger screens
        if (windowWidth <= 1650) {
            return;
        }
        
        sphereVisible = true;
        currentProjects = projects;
        currentImageIndex = 0;
        
        // Start position animation
        updateSpherePosition();
        
        // Start image timer
        startImageTimer();
    }

    function stopSphereEffect() {
        sphereVisible = false;
        
        // Stop image timer
        stopImageTimer();
        
        // Let the animation continue until scale reaches 0
        if (!animationFrame) {
            updateSpherePosition();
        }
    }

    onMount(() => {
        return () => {
            stopSphereEffect();
        };
    });
</script>

<svelte:window on:mousemove={handleMouseMove} bind:innerWidth={windowWidth} />

<!-- Cursor following sphere -->
{#if (sphereScale > 0.01 || sphereOpacity > 0.01) && currentProjects.length > 0 && windowWidth > 1650}
    <div 
        class="cursor-sphere" 
        style="left: {sphereX - 130}px; top: {sphereY - 130}px; transform: scale({sphereScale}); opacity: {sphereOpacity};"
    >
        <!-- Curved text around the sphere -->
        <svg class="curved-text-svg" width="260" height="260" viewBox="0 0 260 260">
            <defs>
                <path id="circle-path" d="M 130,130 m -110,0 a 110,110 0 1,1 220,0 a 110,110 0 1,1 -220,0" />
            </defs>
            <text class="curved-text" font-family="Arial, sans-serif" font-size="14" font-weight="bold" fill="#666" letter-spacing="2px">
                <textPath href="#circle-path" startOffset="0%">
                    {curvedText}
                </textPath>
            </text>
        </svg>
        
        <div class="sphere-image-container">
            <img 
                src={currentProjects[currentImageIndex].image} 
                alt={currentProjects[currentImageIndex].title}
                class="sphere-image"
            />
        </div>
    </div>
{/if}

<ScrollEffect>
    {#each projectCategories as category}
        <section style="padding-left: 13px; padding-right: 13px; margin-bottom: 50px;" id="{category.id}">
            <div class="container" style="max-width: 1000px;">

                <div 
                    class="row category-header" 
                    style="cursor: pointer;" 
                    on:click={() => {
                        collapsedSections[category.id] = !collapsedSections[category.id];
                        // Hide sphere if section just got uncollapsed
                        if (!collapsedSections[category.id]) {
                            stopSphereEffect();
                        }
                    }}
                    on:mouseenter={(event) => {
                        
                        sphereX =  200;
                        sphereY =  event.clientY;
                        if (collapsedSections[category.id]) {
                            startSphereEffect(category.projects);
                        }
                    }}
                    on:mouseleave={stopSphereEffect}
                >
                    <div class="col-12">
                        <div>
                            <h2 class="text-uppercase" style="letter-spacing: 0.15em;">
                                {category.title}
                                    <button class="btn btn-outline-primary">
                                        {#if collapsedSections[category.id]}
                                            Show {category.projects.length} projects ▼
                                        {:else}
                                            Hide projects ▲
                                        {/if}
                                    </button>
                                <span>
                                </span>
                            </h2>
                            <h4 style="line-height: 1.4em;">
                                {@html category.description}
                            </h4>
                        </div>
                    </div>
                </div>

            {#if !collapsedSections[category.id]}
                <div class="row g-4 justify-content-center" style="margin: auto">
                    {#each category.projects as project, index}
                        <div class="col-lg-4 col-md-4 col-sm-6 col-12 project-card" style="margin-bottom: 50px; display: flex; justify-content: center; animation-delay: {index * 0.1}s;">
                            <div class="h-100">
                                <a href="{project.link}" class="text-decoration-none">
                                    <div class="card h-100 border-0 shadow-sm" style="width: 300px">
                                        <div class="overflow-hidden">
                                            <center>
                                                <img src={project.image} alt={project.title} class="card-img-top" style="margin: auto; height: 300px; width: auto; object-fit: cover; aspect-ratio: 1;">
                                            </center>
                                        </div>
                                        <div class="card-body">
                                            <h4 style="text-transform: uppercase; color: black; margin-bottom: 5px">
                                                {project.title}
                                                <small class="fw-normal text-muted">({project.year})</small>
                                            </h4>
                                            <p class="card-text text-muted" style="line-height: 1.2em;">{project.description}</p>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                    {/each}
                </div>
            {/if}

            </div>
        </section>
    {/each}
</ScrollEffect>

<style>
    .colored-dash {
        position: relative;
        top: -2px;
        display: inline-block;
        margin-left: 5px;
        width: 80px;
        height: 4px;
        background: -webkit-linear-gradient(90deg, #456df3 0%, #e66cb8 100%);
        background: -moz-linear-gradient(90deg, #456df3 0%, #e66cb8 100%);
        background: -o-linear-gradient(90deg, #456df3 0%, #e66cb8 100%);
        background: linear-gradient(90deg, #456df3 0%, #e66cb8 100%);
        filter: blur(1px);
        -o-filter: blur(1px);
        -ms-filter: blur(1px);
        -moz-filter: blur(1px);
        -webkit-filter: blur(1px);
        border-radius: 5px;
    }

    .cursor-sphere {
        position: fixed;
        width: 240px;
        height: 240px;
        pointer-events: none;
        z-index: 9999;
        transform-origin: center;
    }

    .curved-text-svg {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        animation: rotate 8s linear infinite;
    }

    .curved-text {
        text-transform: uppercase;
        opacity: 0.7;
    }

    @keyframes rotate {
        from {
            transform: rotate(360deg);
        }
        to {
            transform: rotate(0deg);
        }
    }

    .sphere-image-container {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        width: 160px;
        height: 160px;
        border-radius: 50%;
        overflow: hidden;
        box-shadow: 0 8px 32px rgba(0, 0, 0, 0.3);
        border: 3px solid rgba(255, 255, 255, 0.8);
        background: white;
        display: flex;
        align-items: center;
        justify-content: center;
    }

    .sphere-image {
        width: 100%;
        height: 100%;
        object-fit: cover;
        transition: opacity 0.3s ease;
    }

    .category-header {
        position: relative;
    }

    .category-header:hover h2 {
        transform: translateX(2px);
        transition: transform 0.2s ease;
    }

    /* Project card animation - initially hidden */
    .project-card {
        opacity: 0;
        transform: scale(0.3) rotate(10deg);
        animation: projectPoof 0.4s cubic-bezier(0.34, 1.56, 0.64, 1) forwards;
    }

    @keyframes projectPoof {
        0% {
            opacity: 0;
            transform: scale(0.3) rotate(5deg);
        }
        50% {
            opacity: 0.8;
            transform: scale(1.05) rotate(-2deg);
        }
        70% {
            opacity: 1;
            transform: scale(0.95) rotate(1deg);
        }
        100% {
            opacity: 1;
            transform: scale(1) rotate(0deg);
        }
    }
</style>