<script>
    import ScrollEffect from './ScrollEffect.svelte';
    import { onMount, onDestroy } from 'svelte';

    let artCollaborations = [
        {
            title: "EAT.BITZ",
            link: "/work/eat-bitz",
            image: "img/eat-bitz/event_1.jpg",
            description: "A data-driven oracle experience for exploring the biodiversity of the kitchen. Interactive installation at Venn Canteen, Porto.",
            year: 2026
        },
        {
            title: "Eyes on the Field: Porto",
            link: "/work/eyes-on-the-field",
            image: "img/eyes-on-the-field/field_1.jpg",
            description: "Farm visit and biodiversity dinner event using BITZ to observe and identify organisms, transformed into a multi-sensory dinner. S+T+ARTS EU residency.",
            year: 2025
        },
        {
            title: "BITZ",
            link: "/work/bitz",
            image: "img/bitz/bitz_logo.jpg",
            description: "A digital tool for identifying and learning about the organisms around you. S+T+ARTS EU residency.",
            year: 2025
        },
        {
            title: "WTFood",
            link: "work/wtfood",
            image: "img/wtfood.png",
            description: "Using AI to uncover the glitches of the food system. S+T+ARTS EU residency.",
            year: 2024
        },
    ]

    let educationProjects = [
        {
            title: "LLM Workshops",
            link: "https://rubengr.es/llm_lab/",
            image: "img/llmlab.png",
            description: "7-part hands-on workshop series covering embeddings, Word2Vec, tokenization, the LLM Playground, data pipelines, and RAG with LangFlow.",
            year: 2024
        },
        {
            title: "Visualizing RAGs",
            link: "/work/visualizing-rags",
            image: "img/rags.jpg",
            description: "Teaching tool to explain the inner workings of AI question-answering systems through interactive visualization.",
            year: 2025
        },
        {
            title: "Tic-tac-toe matchbox AI",
            link: "/blog/menace",
            image: "img/menace.jpg",
            description: "Mechanical learning system from the 1960s using matchboxes to learn tic-tac-toe, demonstrating fundamental AI principles with everyday objects.",
            year: 2024
        },
        {
            title: "Drawing2Map",
            link: "/work/drawing2map",
            image: "img/drawing2map/thumb.jpg",
            description: "Web interface for Seg2Sat that helps users understand the relationship between hand-drawn concepts and satellite imagery. Built using HuggingFace's inference endpoint.",
            year: 2023
        }
    ];

    let genAIProjects = [
        {
            title: "GouvX",
            link: "work/gouvx",
            image: "img/gouvx/gouvx_logo.jpg",
            description: "A chatbot using retrieval augmented generation to help you navigate French law.",
            year: 2023
        },
        {
            title: "Seg2Sat",
            link: "https://github.com/RubenGres/Seg2Sat",
            image: "img/seg2sat.jpg",
            description: "Create aerial view images in any style you want. Project made with IGN FLAIR1 dataset, StableDiffusion, and ControlNet.",
            year: 2023
        },
        {
            title: "Infinite Canvas",
            link: "https://rubengr.es/blog/infinitecanvas/",
            image: "img/canvas.jpg",
            description: "Start creating with others using AI image generation in this shared infinite canvas. Powered by StableDiffusion and ReactJS.",
            year: 2022
        },
        {
            title: "This SCP does not exist",
            link: "https://www.thisscpdoesnotexist.com/",
            image: "img/tsdne.jpg",
            description: "Generate custom SCP from a simple prompt using GPT4. Over three thousand entities have been generated by the community.",
            year: 2021
        }
    ];

    let gameProjects = [
        {
            title: "A Bug's Day",
            link: "https://ohmlet.itch.io/a-bugs-day",
            image: "img/fifi.png",
            description: "A firefly is caught in a dull, colorless routine. GMTK 2025 GameJam.",
            year: 2025
        },
        {
            title: "Dad knows (siege) best",
            link: "https://www.youtube.com/watch?v=ofAcTvuybvY",
            image: "img/siege.jpg",
            description: "Lead an army of LLM soldier agents from the grave. Built during Mistral x HF Hackaton 2025.",
            year: 2025
        },
        {
            title: "Zoomies",
            link: "https://ohmlet.itch.io/zoomies",
            image: "https://img.itch.zone/aW1nLzE3NDQ4OTYxLmpwZw==/315x250%23c/p%2BHryy.jpg",
            description: "Play as an exploited employee in corporate hell. GMTK 2024 GameJam.",
            year: 2024
        },
        {
            title: "SnipIt",
            link: "https://ohmlet.itch.io/snip-it",
            image: "img/snipit.jpg",
            description: "Snip away and explore famous paintings in a whole new dimension. First place in the 2023 Hugging Face Game JAM.",
            year: 2023
        },
        {
            title: "Pug Heist",
            link: "https://ohmlet.itch.io/pug-heists",
            image: "img/pug.jpg",
            description: "A strange little puzzle game made for GTMK 2022. Solve every level and escape to safety.",
            year: 2022
        },
        {
            title: "Unwanted Roommate",
            link: "https://ohmlet.itch.io/unwanted-roommate",
            image: "img/unwantedroommate.jpg",
            description: "Deal with your inescapable anxiety, your unwanted roommate. Made for GMTK 2021 Game Jam",
            year: 2021
        },
        {
            title: "VR Handglider",
            link: "https://github.com/RubenGres/VRHanglider",
            image: "img/planeur.jpg",
            description: "Procedural world generator and flight simulator in VR using Unity. The plane is controlled via a microcontroller.",
            year: 2020
        },
        {
            title: "Out Of Control(s)",
            link: "https://ohmlet.itch.io/out-of-controls",
            image: "img/outofcontrols.jpg",
            description: "You have a limited number of key presses before you run out of controls. Made for GMTK 2020 Game Jam.",
            year: 2020
        },
        {
            title: "Blastoff",
            link: "https://github.com/RubenGres/Blastoff",
            image: "img/blastoff.jpg",
            description: "Procedural mining game in Java. Custom game engine, perlin noise, and cellular automatas for terrain generation.",
            year: 2018
        }
    ];

    let otherProjects = [
        {
            title: "Bad Apple Animation",
            link: "https://www.youtube.com/watch?v=LD4D09EVcDY&t=112s",
            image: "img/badapple.jpg",
            description: "A Blender animation of the opening of Bad Apple rendered on an Etch-A-Sketch. The video is currently reaching 333k views!",
            year: 2020
        },
        {
            title: "Flocking Sandbox",
            link: "https://github.com/RubenGres/FlockingSandbox",
            image: "img/boidsjs.jpg",
            description: "Boids algorithm in p5.js. You can spawn a fish or a shark; the sharks will try to eat the fishes as they try to escape.",
            year: 2020
        }
    ];

    let projectCategories = [
        {
            title: "Creative Tech and AI for Artists",
            id: "art",
            description: `
                <p> I work alongside artists in residency, bringing AI, data visualization, and development expertise to their creative practice.
                Our work has been presented at Rotterdam's Nieuw Instituut, Belgrade's Palace of Science, and other international venues. </p>
            `,
            projects : artCollaborations
        },
        {
            title: "Interactive Tools for AI Education",
            id: "education",
            description: `
                <p>I believe in making complex AI concepts accessible through hands-on learning and visual tools.
                I teach at graduate level and work with educational organizations to bring AI education to younger audiences.</p>
            `,
            projects: educationProjects
        },
        {
            title: "Generative AI projects",
            id: "genai",
            description: `
                <p> I explore generative AI to develop practical applications and creative tools for diverse audiences.
                I co-founded <a href="http://latentminds.co">LatentMinds</a>, where we develop experimental tools that redefine the boundaries of AI-assisted creativity.</p>
            `,
            projects : genAIProjects
        },
        {
            title: "Game development",
            id: "games",
            description: `
                <p> I explore unconventional gameplays through game jams, personal projects, and a commercial game soon to be announced.
                I collaborate with friends within <a href="https://ohmlet.itch.io">RockBottom</a>, a collective making small experimental games.</p>
            `,
            projects : gameProjects
        },
        {
            title: "Miscellaneous projects",
            id: "misc",
            description:`
                <p>Experiments, 3D modeling and older projects that didn't fit in any category.<p>
            `,
            projects : otherProjects
        },
    ]

    let collapsedSections = {};

    for (let category of projectCategories) {
        collapsedSections[category.id] = true;
    }

    // Sphere functionality
    let sphereVisible = false;
    let sphereScale = 0;
    let sphereOpacity = 0;
    let sphereX = 0;
    let sphereY = 0;
    let targetX = 0;
    let targetY = 0;
    let currentImageIndex = 0;
    let currentProjects = [];
    let animationFrame;
    let imageTimerInterval;
    let windowWidth = 0;
    
    // Generate curved text from project names
    $: curvedText = currentProjects.length > 0 
        ? (currentProjects.map(p => p.title.toUpperCase()).join(' • ') + ' • ').repeat(5).slice(0, 66) + "..."
        : 'SNEAK PEEK • '.repeat(8);

    function updateSpherePosition() {
        // Smooth following with delay (faster movement)
        const lerp = 0.03;
        sphereY += (targetY - sphereY) * lerp;
        
        // Animate scale and opacity together
        const targetScale = sphereVisible ? 1 : 0;
        const targetOpacity = sphereVisible ? 1 : 0;
        const scaleLerp = 0.15;
        const opacityLerp = 0.12;
        
        sphereScale += (targetScale - sphereScale) * scaleLerp;
        sphereOpacity += (targetOpacity - sphereOpacity) * opacityLerp;
        
        if (sphereVisible || sphereScale > 0.01 || sphereOpacity > 0.01) {
            animationFrame = requestAnimationFrame(updateSpherePosition);
        }
    }

    function handleMouseMove(event) {
        if (sphereVisible) {
            // Offset position to lower right to avoid blocking view
            targetY = event.clientY;
        }
    }

    function startImageTimer() {
        // Clear any existing timer
        if (imageTimerInterval) {
            clearInterval(imageTimerInterval);
        }
        
        // Set up new timer to change image every 1 second
        imageTimerInterval = setInterval(() => {
            if (sphereVisible && currentProjects.length > 0) {
                currentImageIndex = (currentImageIndex + 1) % currentProjects.length;
            }
        }, 1000); // 1000ms = 1 second
    }

    function stopImageTimer() {
        if (imageTimerInterval) {
            clearInterval(imageTimerInterval);
            imageTimerInterval = null;
        }
    }

    function startSphereEffect(projects) {
        // Only show sphere on larger screens
        if (windowWidth <= 1650) {
            return;
        }
        
        sphereVisible = true;
        currentProjects = projects;
        currentImageIndex = 0;
        
        // Start position animation
        updateSpherePosition();
        
        // Start image timer
        startImageTimer();
    }

    function stopSphereEffect() {
        sphereVisible = false;
        
        // Stop image timer
        stopImageTimer();
        
        // Let the animation continue until scale reaches 0
        if (!animationFrame) {
            updateSpherePosition();
        }
    }

    onMount(() => {});

    onDestroy(() => {
        // Cancel RAF immediately — no need to animate to 0 after component is gone
        if (animationFrame) {
            cancelAnimationFrame(animationFrame);
            animationFrame = null;
        }
        stopImageTimer();
    });
</script>

<svelte:window on:mousemove={handleMouseMove} bind:innerWidth={windowWidth} />

<!-- Cursor following sphere -->
{#if (sphereScale > 0.01 || sphereOpacity > 0.01) && currentProjects.length > 0 && windowWidth > 1650}
    <div 
        class="cursor-sphere" 
        style="left: {sphereX - 130}px; top: {sphereY - 130}px; transform: scale({sphereScale}); opacity: {sphereOpacity};"
    >
        <!-- Curved text around the sphere -->
        <svg class="curved-text-svg" width="260" height="260" viewBox="0 0 260 260">
            <defs>
                <path id="circle-path" d="M 130,130 m -110,0 a 110,110 0 1,1 220,0 a 110,110 0 1,1 -220,0" />
            </defs>
            <text class="curved-text" font-family="Arial, sans-serif" font-size="14" font-weight="bold" fill="#666" letter-spacing="2px">
                <textPath href="#circle-path" startOffset="0%">
                    {curvedText}
                </textPath>
            </text>
        </svg>
        
        <div class="sphere-image-container">
            <img
                src={currentProjects[currentImageIndex].image}
                alt={currentProjects[currentImageIndex].title}
                class="sphere-image"
                loading="lazy"
            />
        </div>
    </div>
{/if}

<ScrollEffect>
    {#each projectCategories as category, i}
        <section style="padding-left: 13px; padding-right: 13px; margin-bottom: 50px;" id="{category.id}">
            <div class="container" style="max-width: 1000px;">

                <div
                    class="category-header"
                    on:click={() => {
                        collapsedSections[category.id] = !collapsedSections[category.id];
                        if (!collapsedSections[category.id]) {
                            stopSphereEffect();
                        }
                    }}
                    on:mouseenter={(event) => {
                        sphereX = 200;
                        sphereY = event.clientY;
                        if (collapsedSections[category.id]) {
                            startSphereEffect(category.projects);
                        }
                    }}
                    on:mouseleave={stopSphereEffect}
                >
                    <span class="category-num" aria-hidden="true">{i + 1 < 10 ? '0' : ''}{i + 1}</span>
                    <div class="category-header-top">
                        <h2 class="category-title">{category.title}</h2>
                        <button class="toggle-btn" aria-expanded={!collapsedSections[category.id]}>
                            {#if collapsedSections[category.id]}
                                <span>{category.projects.length} projects</span>
                                <svg class="toggle-chevron" width="16" height="16" viewBox="0 0 16 16" fill="none"><path d="M4 6l4 4 4-4" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>
                            {:else}
                                <span>hide</span>
                                <svg class="toggle-chevron expanded" width="16" height="16" viewBox="0 0 16 16" fill="none"><path d="M4 6l4 4 4-4" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>
                            {/if}
                        </button>
                    </div>
                    <div class="category-description">
                        {@html category.description}
                    </div>
                </div>

            {#if !collapsedSections[category.id]}
                <div class="projects-grid">
                    {#each category.projects as project, index}
                        <div class="project-card" class:tilt-left={index % 2 === 0} class:tilt-right={index % 2 !== 0} style="animation-delay: {index * 0.08}s;">
                            <a
                                href="{project.link}"
                                class="project-card-link"
                                target={project.link.startsWith('http') ? '_blank' : null}
                                rel={project.link.startsWith('http') ? 'noopener noreferrer' : null}
                            >
                                <div class="project-card-img-wrap">
                                    <img src={project.image} alt={project.title} class="project-card-img" loading="lazy">
                                </div>
                                <div class="project-card-body">
                                    <h4 class="project-card-title">
                                        {project.title}
                                        <small class="project-card-year">({project.year})</small>
                                    </h4>
                                    <p class="project-card-desc">{project.description}</p>
                                </div>
                            </a>
                        </div>
                    {/each}
                </div>
            {/if}

            </div>
        </section>
    {/each}
</ScrollEffect>

<style>
    .colored-dash {
        position: relative;
        top: -2px;
        display: inline-block;
        margin-left: 5px;
        width: 80px;
        height: 4px;
        background: -webkit-linear-gradient(90deg, #456df3 0%, #e66cb8 100%);
        background: -moz-linear-gradient(90deg, #456df3 0%, #e66cb8 100%);
        background: -o-linear-gradient(90deg, #456df3 0%, #e66cb8 100%);
        background: linear-gradient(90deg, #456df3 0%, #e66cb8 100%);
        filter: blur(1px);
        -o-filter: blur(1px);
        -ms-filter: blur(1px);
        -moz-filter: blur(1px);
        -webkit-filter: blur(1px);
        border-radius: 5px;
    }

    .cursor-sphere {
        position: fixed;
        width: 240px;
        height: 240px;
        pointer-events: none;
        z-index: 9999;
        transform-origin: center;
    }

    .curved-text-svg {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        animation: rotate 8s linear infinite;
    }

    .curved-text {
        text-transform: uppercase;
        opacity: 0.7;
    }

    @keyframes rotate {
        from {
            transform: rotate(360deg);
        }
        to {
            transform: rotate(0deg);
        }
    }

    .sphere-image-container {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        width: 160px;
        height: 160px;
        border-radius: 50%;
        overflow: hidden;
        box-shadow: 0 8px 32px rgba(0, 0, 0, 0.3);
        border: 3px solid rgba(255, 255, 255, 0.8);
        background: white;
        display: flex;
        align-items: center;
        justify-content: center;
    }

    .sphere-image {
        width: 100%;
        height: 100%;
        object-fit: cover;
        transition: opacity 0.3s ease;
    }

    .category-header {
        position: relative;
        cursor: pointer;
        padding: 1.25rem 0 1rem 0;
        border-top: 2px solid #eee;
        box-shadow: inset 3px 0 0 transparent;
        transition: box-shadow 0.3s cubic-bezier(0.34, 1.56, 0.64, 1), padding-left 0.3s cubic-bezier(0.34, 1.56, 0.64, 1);
        overflow: hidden;
    }

    .category-header:hover {
        box-shadow: inset 3px 0 0 #1a1a1a;
        padding-left: 10px;
    }

    .category-num {
        position: absolute;
        right: -0.05em;
        top: 50%;
        transform: translateY(-60%);
        font-size: 7rem;
        font-weight: 900;
        color: #000;
        opacity: 0.04;
        line-height: 1;
        user-select: none;
        pointer-events: none;
        letter-spacing: -0.05em;
        transition: opacity 0.3s ease;
    }

    .category-header:hover .category-num {
        opacity: 0.07;
    }

    .category-header-top {
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: 1rem;
    }

    .category-title {
        font-size: 1.3rem;
        font-weight: 700;
        text-transform: uppercase;
        letter-spacing: 0.12em;
        color: #1a1a1a;
        margin: 0;
        line-height: 1.3;
        background-image: linear-gradient(currentColor, currentColor);
        background-size: 0% 2px;
        background-repeat: no-repeat;
        background-position: left bottom;
        padding-bottom: 2px;
        transition: background-size 0.35s cubic-bezier(0.25, 1, 0.5, 1), transform 0.25s cubic-bezier(0.34, 1.56, 0.64, 1);
    }

    .category-header:hover .category-title {
        background-size: 100% 2px;
        transform: translateX(4px);
    }

    .toggle-btn {
        display: inline-flex;
        align-items: center;
        gap: 6px;
        padding: 6px 14px;
        font-size: 0.78rem;
        font-weight: 600;
        text-transform: uppercase;
        letter-spacing: 0.08em;
        color: #555;
        background: #f4f4f4;
        border: 1px solid #ddd;
        border-radius: 20px;
        cursor: pointer;
        white-space: nowrap;
        flex-shrink: 0;
        transition: background 0.2s ease, color 0.2s ease, border-color 0.2s ease, transform 0.15s cubic-bezier(0.34, 1.56, 0.64, 1);
    }

    .toggle-btn:hover,
    .category-header:hover .toggle-btn {
        background: #1a1a1a;
        color: white;
        border-color: transparent;
    }

    .toggle-btn:active {
        transform: scale(0.88);
    }

    .toggle-chevron {
        transition: transform 0.35s cubic-bezier(0.34, 1.56, 0.64, 1);
    }

    .toggle-chevron.expanded {
        transform: rotate(180deg);
    }

    .category-description {
        margin-top: 0.6rem;
        color: #555;
        font-size: 0.95rem;
        line-height: 1.5;
        max-width: 720px;
    }

    .category-description :global(p) {
        margin: 0;
    }

    .category-description :global(a) {
        color: #05364d;
        text-decoration: underline;
    }

    .category-description :global(a:hover) {
        color: #efb6df;
    }

    /* Projects grid — CSS Grid, no Bootstrap dependency */
    .projects-grid {
        display: grid;
        grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
        gap: 2rem;
        margin-top: 1.5rem;
    }

    /* Project card */
    .project-card {
        opacity: 0;
        transform: scale(0.3) rotate(10deg);
        animation: projectPoof 0.4s cubic-bezier(0.34, 1.56, 0.64, 1) forwards;
    }

    .project-card-link {
        display: block;
        text-decoration: none;
        color: inherit;
        background: white;
        border-radius: 8px;
        box-shadow: 0 2px 8px rgba(0,0,0,0.08);
        overflow: hidden;
        height: 100%;
        transition: box-shadow 0.3s ease, transform 0.3s cubic-bezier(0.34, 1.56, 0.64, 1);
    }

    .tilt-left .project-card-link:hover {
        box-shadow: 0 8px 24px rgba(0,0,0,0.13);
        transform: translateY(-5px) rotate(-1.5deg);
    }

    .tilt-right .project-card-link:hover {
        box-shadow: 0 8px 24px rgba(0,0,0,0.13);
        transform: translateY(-5px) rotate(1.5deg);
    }

    .project-card-img-wrap {
        overflow: hidden;
        aspect-ratio: 1;
    }

    .project-card-img {
        width: 100%;
        height: 100%;
        object-fit: cover;
        display: block;
        transition: transform 0.4s cubic-bezier(0.25, 1, 0.5, 1);
    }

    .project-card-link:hover .project-card-img {
        transform: scale(1.06);
    }

    .project-card-body {
        padding: 1rem;
    }

    .project-card-title {
        text-transform: uppercase;
        color: black;
        margin-bottom: 5px;
        font-size: 1rem;
    }

    .project-card-year {
        font-weight: 400;
        color: #6c757d;
    }

    .project-card-desc {
        color: #6c757d;
        line-height: 1.3em;
        font-size: 0.95rem;
        margin: 0;
    }

    @keyframes projectPoof {
        0% {
            opacity: 0;
            transform: scale(0.3) rotate(5deg);
        }
        50% {
            opacity: 0.8;
            transform: scale(1.05) rotate(-2deg);
        }
        70% {
            opacity: 1;
            transform: scale(0.95) rotate(1deg);
        }
        100% {
            opacity: 1;
            transform: scale(1) rotate(0deg);
        }
    }
</style>